# Generated by Django 3.1.2 on 2020-10-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='menu_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
